Added notify-linter-on-failure

diff --git a/.tekton/pre-commit.yaml b/.tekton/pre-commit.yaml
--- a/.tekton/pre-commit.yaml
+++ b/.tekton/pre-commit.yaml
@@ -15,6 +15,7 @@ metadata:
     # with taskRef and it will automatically be embedded into our pipeline.
     pipelinesascode.tekton.dev/task: "git-clone"
 
+
     # Use maven task from hub
     # pipelinesascode.tekton.dev/task-1: "[pre-commit]"
 
@@ -22,7 +23,7 @@ metadata:
     # https://hub.tekton.dev/
     # example:
     #   pipelinesascode.tekton.dev/task-2: "[github-add-labels]"
-    #   pipelinesascode.tekton.dev/task-2: "[.tekton/task/github-add-labels.yaml]"
+    pipelinesascode.tekton.dev/task-2: "[.tekton/tasks/github-add-comment.yaml]"
 
     # How many runs we want to keep attached to this event
     pipelinesascode.tekton.dev/max-keep-runs: "3"
@@ -36,11 +37,14 @@ spec:
       value: "{{ revision }}"
     - name: pull_request_number
       value: "{{ pull_request_number }}"
+    - name: git_auth_secret
+      value: "{{ git_auth_secret }}"
   pipelineSpec:
     params:
       - name: repo_url
       - name: revision
       - name: pull_request_number
+      - name: git_auth_secret
     workspaces:
       - name: source
       - name: basic-auth
@@ -68,6 +72,9 @@ spec:
           - name: source
             workspace: source
         taskSpec:
+          results:
+            - name: linter-output
+              description: Output of pre-commit run
           workspaces:
             - name: source
           steps:
@@ -75,7 +82,41 @@ spec:
               image: quay.io/redhat-emea-ssa-team/hetzner-ocp4-pre-commit:latest
               workingDir: $(workspaces.source.path)
               script: |
-                pre-commit run --color=never --all-files
+                set -euxo pipefail
+
+                echo -e " 💀 There was an error during pre-commit / linter:\n\n```" \
+                  > $(workspaces.source.path)/notify-linter-on-failure.txt
+
+                pre-commit run --color=never --all-files \
+                  | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2};?)?)?[mGK]//g" \
+                  | tee -a $(workspaces.source.path)/notify-linter-on-failure.txt
+
+                RC=$?
+                echo "Return code $RC"
+
+                echo -e '\n```\n' \
+                  > $(workspaces.source.path)/notify-linter-on-failure.txt
+
+                exit $?
+
+    finally:
+      - name: notify-linter-on-failure
+        workspaces:
+          - name: comment-file
+            workspace: source
+        when:
+          - input: $(tasks.pre-commit.status)
+            operator: in
+            values: ["Failed"]
+        params:
+          - name: REQUEST_URL
+            value: "$(params.repo_url)/pull/$(params.pull_request_number)"
+          - name: PAC_GITHUB_SECRET
+            value: "$(params.git_auth_secret)"
+          - name: COMMENT_OR_FILE
+            value: "notify-linter-on-failure.txt"
+        taskRef:
+          name: github-add-comment
 
   workspaces:
     - name: source
